#if !defined(AFX_AVERAGEFUNCTION_H__85ACE082_A73D_404D_AD48_618CD3B28B4A__INCLUDED_)
#define AFX_AVERAGEFUNCTION_H__85ACE082_A73D_404D_AD48_618CD3B28B4A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAverageFunction wrapper class

class CAverageFunction : public COleDispatchDriver
{
public:
	CAverageFunction() {}		// Calls COleDispatchDriver default constructor
	CAverageFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAverageFunction(const CAverageFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeNulls();
	void SetIncludeNulls(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AVERAGEFUNCTION_H__85ACE082_A73D_404D_AD48_618CD3B28B4A__INCLUDED_)
