#if !defined(AFX_INSTRUMENTCIRCLE_H__7C191477_7F94_4D81_88BE_B9B5BE5801E3__INCLUDED_)
#define AFX_INSTRUMENTCIRCLE_H__7C191477_7F94_4D81_88BE_B9B5BE5801E3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CInstrumentCircle wrapper class

class CInstrumentCircle : public CWnd
{
protected:
	DECLARE_DYNCREATE(CInstrumentCircle)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x74de98ee, 0xde61, 0x46c1, { 0xaa, 0x56, 0x96, 0x16, 0xc1, 0xe4, 0x9e, 0x90 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetMimDeg();
	void SetMimDeg(short);
	short GetMaxDeg();
	void SetMaxDeg(short);
	short GetMinValue();
	void SetMinValue(short);
	short GetMaxValue();
	void SetMaxValue(short);
	short GetDivCount();
	void SetDivCount(short);
	double GetRealValue();
	void SetRealValue(double);
	double GetAimValue();
	void SetAimValue(double);
	double GetNumberFont();
	void SetNumberFont(double);
	double GetLabFont();
	void SetLabFont(double);
	long GetLabX();
	void SetLabX(long);
	long GetLabY();
	void SetLabY(long);
	CString GetLabText();
	void SetLabText(LPCTSTR);
	CString GetLabTextLine2();
	void SetLabTextLine2(LPCTSTR);
	long GetLabX2();
	void SetLabX2(long);
	long GetLabY2();
	void SetLabY2(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_INSTRUMENTCIRCLE_H__7C191477_7F94_4D81_88BE_B9B5BE5801E3__INCLUDED_)
