#if !defined(AFX_INSTRUMENTPANEL_H__36A3867E_86D0_4830_935A_06B93CF449C8__INCLUDED_)
#define AFX_INSTRUMENTPANEL_H__36A3867E_86D0_4830_935A_06B93CF449C8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CInstrumentPanel wrapper class

class CInstrumentPanel : public CWnd
{
protected:
	DECLARE_DYNCREATE(CInstrumentPanel)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9542050c, 0x6b62, 0x4250, { 0x86, 0x5f, 0x46, 0x57, 0x9f, 0xa5, 0x76, 0xb8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetFyDeg();
	void SetFyDeg(short);
	short GetGzDeg();
	void SetGzDeg(short);
	short GetDirection();
	void SetDirection(short);
	short GetApHeight();
	void SetApHeight(short);
	short GetAimHeight();
	void SetAimHeight(short);
	short GetAirSpeed();
	void SetAirSpeed(short);
	short GetAimAirSpeed();
	void SetAimAirSpeed(short);
	short GetAimDirection();
	void SetAimDirection(short);
	float GetHeading();
	void SetHeading(float);

// Operations
public:
	void UpDate(short GzDeg, short FyDeg, short Direction, short AimDirection, short AirSpeed, short AimAirSpeed, short ApHeight, short AimHeight, float Heading);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_INSTRUMENTPANEL_H__36A3867E_86D0_4830_935A_06B93CF449C8__INCLUDED_)
