#if !defined(AFX_PAGE_H__36AD87F9_2B67_4300_8699_0220A65F9F2A__INCLUDED_)
#define AFX_PAGE_H__36AD87F9_2B67_4300_8699_0220A65F9F2A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPage wrapper class

class CPage : public COleDispatchDriver
{
public:
	CPage() {}		// Calls COleDispatchDriver default constructor
	CPage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPage(const CPage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Next();
	void Previous();
	long GetMaxPointsPerPage();
	void SetMaxPointsPerPage(long nNewValue);
	long GetCurrent();
	void SetCurrent(long nNewValue);
	BOOL GetScaleLastPage();
	void SetScaleLastPage(BOOL bNewValue);
	long GetCount();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PAGE_H__36AD87F9_2B67_4300_8699_0220A65F9F2A__INCLUDED_)
