#if !defined(AFX_PIEOTHERSLICE_H__A1756C3D_DD91_436E_AE65_8D8E957C0A0B__INCLUDED_)
#define AFX_PIEOTHERSLICE_H__A1756C3D_DD91_436E_AE65_8D8E957C0A0B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPieOtherSlice wrapper class

class CPieOtherSlice : public COleDispatchDriver
{
public:
	CPieOtherSlice() {}		// Calls COleDispatchDriver default constructor
	CPieOtherSlice(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPieOtherSlice(const CPieOtherSlice& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	double GetValue();
	void SetValue(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PIEOTHERSLICE_H__A1756C3D_DD91_436E_AE65_8D8E957C0A0B__INCLUDED_)
