//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GStation.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GSTATION_DIALOG             102
#define IDD_SET_SAFE                    107
#define IDD_SET_CAMERA                  111
#define IDD_SET_SERIALPORT              112
#define IDD_SET_INTERFACE               113
#define IDR_MAINFRAME                   128
#define IDI_LEDOFF                      130
#define IDI_LEDON                       131
#define IDI_LEDWARN                     132
#define IDR_MENU                        134
#define IDR_MENU_MOUSE                  135
#define IDI_UP_WAYLINE                  137
#define IDI_DOWN_WAYPOINT               138
#define IDD_DLG_DOWN_WAYPOINT           139
#define IDD_DLG_WAYPOINT_DOWN           139
#define IDD_DLG_DOWN_PHOTONUM           140
#define IDD_SET_AIRSPEED                141
#define IDD_SET_ALTITUDE                142
#define IDD_SET_PITCH_ROLL              143
#define IDD_SET_PHOTO                   144
#define IDD_DLG_LAYER                   145
#define IDD_SET_VERSION                 147
#define IDD_SET_SETUP                   148
#define IDB_BITMAP_SETUP                150
#define IDI_LAYER                       155
#define IDI_INQUIRE_PHOTONUM            157
#define IDI_DOWN_PHOTODATA              158
#define IDI_HANDPHOTOONE                159
#define IDI_STARTCONTINUEPHOTO          160
#define IDI_STOPCONTINUEPHOTO           161
#define IDI_DISTANCE                    166
#define IDR_TOOLBAR                     168
#define IDI_RECT                        174
#define IDI_CENTER                      176
#define IDI_CLEANTRACK                  177
#define IDI_CLEANUAVWAYPOINT            178
#define IDI_COPYUAVWAYPOINT             179
#define IDI_PROMPTWAYLINE               180
#define IDI_SHOWUAVWAYPOINT             181
#define IDI_WAYLINE                     182
#define IDI_CPV                         184
#define IDI_RUNWAY                      185
#define IDI_SIGNLINE                    186
#define IDI_SIGNPOINT                   187
#define IDI_SIGNPOLY                    188
#define IDI_SIGNPOLYLINE                189
#define IDD_SET_STEERINGENGINE          190
#define IDD_DLG_WAYPOINT_UP             193
#define IDD_DLG_WAYPOINT_EDIT           194
#define IDD_DLG_PIDAdjust               195
#define IDD_DLG_WAYPOINT_SHOW           196
#define IDD_DLG_TAKEOFF_CHECK           197
#define IDB_CHECKBOXES                  198
#define IDD_DLG_SIGN                    199
#define IDD_DOWN_GPS                    200
#define IDD_DOWN_STEERING               201
#define IDD_DOWN_SENSOR                 202
#define IDD_DOWN_MIDDLE                 203
#define IDC_BUTTON_URGENCY_OPEN_UMBRELLA 1003
#define IDC_EDIT_CLIMB_MIN              1004
#define IDC_BUTTON_AUTO_TAKEOFF         1004
#define IDC_EDIT_CLIMB_MAX              1005
#define IDC_BUTTON_START_GLIDE          1005
#define IDC_EDIT_LOWEST_ALT             1006
#define IDC_BUTTON_SEND                 1006
#define IDC_BUTTON_SENDTARGET_WPNUM     1006
#define IDC_EDIT_AIRSPEED_MIN           1007
#define IDC_BUTTON_SEND2                1007
#define IDC_BUTTON_CPV_SPEED            1007
#define IDC_EDIT_AIRSPEED_MAX           1008
#define IDC_EDIT_PILOT_VMIN             1009
#define IDC_BUTTON_SEND3                1009
#define IDC_BUTTON_CPV_DIRECTION        1009
#define IDC_EDIT_PILOT_VMAX             1010
#define IDC_BUTTON_SEND4                1010
#define IDC_EDIT_SERVO_VMAX             1011
#define IDC_EDIT_SERVO_VMIN             1012
#define IDC_BUTTON_APPLY                1013
#define IDC_MSCOMM                      1014
#define IDC_COM_TELE                    1015
#define IDC_BT                          1016
#define IDC_BUTTON_COMTELE              1018
#define IDC_BUTTON_BT                   1019
#define IDC_EDIT_RECEIVED_PACKET_TYPE   1020
#define IDC_BUTTON_CLOSE_COM            1021
#define IDC_EDIT_AIR3                   1026
#define IDC_EDIT_TIME2                  1026
#define IDC_BUTTON_STOP_CAR             1028
#define IDC_BUTTON_OPEN_UMBRELLA        1029
#define IDC_BUTTON_UAV                  1030
#define IDC_BUTTON_PLAY                 1031
#define IDC_EDIT_TARGET_WAYPOINT        1032
#define IDC_EDIT_TARGET_WAYPOINTNUM     1032
#define IDC_EDIT_TARGET_WAYPOINT2       1033
#define IDC_EDIT_SENDTARGET_WPNUM       1033
#define IDC_TOOL_DOWN_WAYPOINT          1034
#define IDC_EDIT_TARGET_WAYPOINT3       1034
#define IDC_EDIT_CPV_DIRECTION          1034
#define IDC_TOOL_INQUIRE_PHOTONUM       1035
#define IDC_EDIT_TARGET_WAYPOINT4       1035
#define IDC_MAP                         1036
#define IDC_EDIT_DOWN_WAYPOIT           1037
#define IDC_TOOL_DOWN_PHOTODATA         1037
#define IDC_EDIT_TARGET_WAYPOINT5       1037
#define IDC_EDIT_CPV_SPEED              1037
#define IDC_RADIO_ALL                   1038
#define IDC_TOOL_HANDPHOTOONE           1038
#define IDC_BUTTON_PAUSE                1038
#define IDC_RADIO_RANGE                 1039
#define IDC_TOOL_STOPCONTINUEPHOTO      1039
#define IDC_BUTTON_CPV                  1039
#define IDC_EDIT_START                  1040
#define IDC_TOOL_STARTCONTINUEPHOTO     1040
#define IDC_EDIT_END                    1041
#define IDC_BUTTON_AIRSPEED_TOZERO      1041
#define IDC_TOOL_LAYER                  1041
#define IDC_BUTTON_AIRSPEED_CAPTURE     1042
#define IDC_BUTTON_AIRSPEED_DEFAULT     1043
#define IDC_BUTTON_AIRSPEED_SET         1044
#define IDC_EDIT_AIRSPEED_VALUE         1045
#define IDC_EDIT_ALTITUDE               1046
#define IDC_BUTTON_SET                  1047
#define IDC_EDIT_PITCH                  1048
#define IDC_EDIT_ROLL                   1049
#define IDC_BUTTON_CAPTURE              1050
#define IDC_RADIO_EQUAL_TIME            1051
#define IDC_BUTTON_TOZERO               1052
#define IDC_RADIO_EQUAL_DISTANCE        1052
#define IDC_EDIT_EQUAL_TIME             1053
#define IDC_EDIT_EQUAL_DISTANCE         1054
#define IDC_COMMONDIALOG                1054
#define IDC_RADIO_ELECTRON_DOOR         1055
#define IDC_EDIT_DIRECTORY              1055
#define IDC_RADIO_STEER_DOOR            1056
#define IDC_BUTTON_NEW                  1056
#define IDC_BUTTON_OPEN                 1057
#define IDC_EDIT_SOFT                   1057
#define IDC_BUTTON_MAP                  1058
#define IDC_EDIT_HARDWARE               1058
#define IDC_COMBO                       1063
#define IDC_COMMONDIALOG1               1065
#define IDC_CHECK_LISTEN                1066
#define IDC_CHECK_FLYLAYER              1067
#define IDC_CHECK_FLYPLANEGPS           1067
#define IDC_COMBO_LAYER                 1068
#define IDC_CHECK_LAYER_WAYLINE         1068
#define IDC_CHECK_LAYER_SIGN            1069
#define IDC_CHECK_FLYLAYER4             1070
#define IDC_CHECK_WAYPOINTSTATION       1070
#define IDC_CHECK_FLYLAYER5             1071
#define IDC_CHECK_WAYPOINTDOWN          1071
#define IDC_CHECK_FLYLAYER6             1072
#define IDC_CHECK_LAYER_SIGN_SHOWSIGN   1072
#define IDC_CHECK_FLYLAYER8             1074
#define IDC_CHECK_MAP_GST               1074
#define IDC_EDIT_TELE_LONGITUDE         1076
#define IDC_EDIT_TELE_LATITUDE          1077
#define IDC_EDIT_TELE_ALTITUDE          1078
#define IDC_EDIT_TELE_GPSSATELLITE      1079
#define IDC_EDIT_TELE_GROUNDSPEED       1080
#define IDC_EDIT_TELE_PITCH             1082
#define IDC_EDIT_TELE_ROLL              1083
#define IDC_EDIT_TELE_DIRECTION         1084
#define IDC_TAB1                        1085
#define IDC_EDIT_TARGET_AIRSPEED        1085
#define IDC_RADIO_LAUNCH1               1087
#define IDC_BUTTON_WP_SAVE              1087
#define IDC_RADIO_LAUNCH2               1088
#define IDC_BUTTON_MODEL_SAVE           1088
#define IDC_BUTTON_SET_LAUNCH           1089
#define IDC_LIST                        1090
#define IDC_EDIT_WP_LONGITUDE           1091
#define IDC_EDIT_WP_LATITUDE            1092
#define IDC_EDIT_WP_AIRSPEED            1093
#define IDC_EDIT_WP_ALTITUDE            1094
#define IDC_EDIT_WP_RADIUS              1095
#define IDC_EDIT_WP_TIME                1096
#define IDC_EDIT_WP_MODEL               1097
#define IDC_COMBO_TOLINE                1098
#define IDC_BUTTON_WP_EDIT              1099
#define IDC_EDIT_WP_LONGITUDE2          1100
#define IDC_BUTTON_GYROSCOPE            1100
#define IDC_EDIT_WP_LATITUDE2           1101
#define IDC_BUTTON_GYROSCOPE2           1101
#define IDC_EDIT_SIGN                   1101
#define IDC_EDIT_WP_AIRSPEED2           1102
#define IDC_SLIDER                      1102
#define IDC_EDIT_WP_ALTITUDE2           1103
#define IDC_EDIT_WP_RADIUS2             1104
#define IDC_EDIT_WP_NUM                 1105
#define IDC_SCROLLBAR                   1105
#define IDC_COMBO_TOGROUND              1106
#define IDC_EDIT_SLIDER                 1106
#define IDC_COMBO_TOSLOPE               1107
#define IDC_INSTRUMENTPANELCTRL         1107
#define IDC_COMBO_PHOTO                 1108
#define IDC_STATIC_BACK                 1108
#define IDC_COMBO_SERVO1                1109
#define IDC_STATIC_TIME                 1109
#define IDC_COMBO_SERVO2                1110
#define IDC_COMBO_SERVO3                1111
#define IDC_EDIT_WP_TIME2               1112
#define IDC_EDIT_WP_MODEL2              1113
#define IDC_STATIC_BACK_POSITION        1113
#define IDC_COMBO_TOLINE2               1114
#define IDC_STATIC_BACK_SPEED           1114
#define IDC_EDIT_WP_NUM2                1115
#define IDC_BUTTON_TEST                 1115
#define IDC_COMBO_TOGROUND2             1116
#define IDC_COMBO_TOSLOPE2              1117
#define IDC_COMBO_PHOTO2                1118
#define IDC_COMBO_SERVO12               1119
#define IDC_EDIT1                       1119
#define IDC_COMBO_SERVO22               1120
#define IDC_EDIT_XD                     1120
#define IDC_EDIT2                       1120
#define IDC_COMBO_SERVO32               1121
#define IDC_EDIT_PDOP                   1121
#define IDC_BUTTON_MODEL_EDIT           1122
#define IDC_EDIT_SNUM                   1122
#define IDC_EDIT_LONG                   1123
#define IDC_INSTRUMENTCIRCLECTRL1       1123
#define IDC_INSTRUMENTCIRCLECTRL        1123
#define IDC_EDIT_LAT                    1124
#define IDC_EDIT_SAL                    1125
#define IDC_EDIT_SPEED                  1126
#define IDC_EDIT_DIRECTION              1127
#define IDC_CHECK_GPSDhSwitch           1157
#define IDC_EDIT_hx                     1158
#define IDC_EDIT_aimHx                  1159
#define IDC_TCHART_PID                  1160
#define IDC_EDIT_GPSDhSwitch            1161
#define IDC_EDIT_dh_P                   1163
#define IDC_EDIT_dh_I                   1164
#define IDC_EDIT_dh_D                   1165
#define IDC_EDIT_pxc                    1166
#define IDC_EDIT_phxz_P                 1168
#define IDC_EDIT_phxz_I                 1169
#define IDC_EDIT_phxz_D                 1170
#define IDC_EDIT_BP                     1171
#define IDC_CHECK_PhxzSwitch            1172
#define IDC_EDIT_PhxzSwitch             1173
#define IDC_EDIT_cj                     1174
#define IDC_EDIT_jmb                    1175
#define IDC_EDIT_hxx                    1176
#define IDC_EDIT_MaxYj                  1186
#define IDC_EDIT_MidYj                  1187
#define IDC_EDIT_MinYj                  1188
#define IDC_COMBO_SelectCH              1190
#define IDC_BTN_SendFyRPV               1191
#define IDC_INSTRUMENTPANELCTRL1        1192
#define IDC_BTN_SendZwRPV               10871
#define IDC_BTN_SendMaxZwRate           10881
#define IDC_BTN_SendKsRPV               10891
#define IDC_BTN_GetYjData               10911
#define IDC_EDIT_CtrlModel              10921
#define IDC_EDIT_PIDModel               10931
#define IDC_CHECK_FySwitch              10941
#define IDC_CHECK_ZwbzSwitch            10951
#define IDC_EDIT_fyDeg                  10961
#define IDC_EDIT_aimFyDeg               10971
#define IDC_EDIT_fyRPV                  10981
#define IDC_EDIT_FySwitch               10991
#define IDC_EDIT_ZwbcSwitch             11001
#define IDC_EDIT_fy_P                   11011
#define IDC_EDIT_fy_I                   11021
#define IDC_EDIT_fy_D                   11031
#define IDC_EDIT_TP                     11041
#define IDC_CHECK_ZwSwitch              11051
#define IDC_BTN_GETPIDDATA              11061
#define IDC_EDIT_zwRate                 11071
#define IDC_EDIT_aimZwRate              11081
#define IDC_EDIT_zwRPV                  11091
#define IDC_EDIT_ZwSwitch               11101
#define IDC_BTN_SendData                11111
#define IDC_EDIT_fxd_P                  11121
#define IDC_EDIT_fxd_I                  11131
#define IDC_EDIT_fxd_D                  11141
#define IDC_BTN_SaveData                11151
#define IDC_EDIT_maxZwRate              11161
#define IDC_BTN_OpenData                11171
#define IDC_CHECK_KsToYm                11181
#define IDC_CHECK_KsSwitch              11191
#define IDC_EDIT_ks                     11201
#define IDC_EDIT_aimKs                  11211
#define IDC_EDIT_ksRPV                  11221
#define IDC_CHECK_GzSwitch              11231
#define IDC_EDIT_KsSwitch               11241
#define IDC_EDIT_ks_ky_P                11251
#define IDC_EDIT_ks_ky_I                11261
#define IDC_EDIT_ks_ky_D                11271
#define IDC_EDIT_ks_kf_P                11281
#define IDC_EDIT_ds                     11291
#define IDC_EDIT_ks_kf_I                11301
#define IDC_EDIT_ks_kf_D                11311
#define IDC_EDIT_fy_gzDeg               11321
#define IDC_BTN_OpenAllCh               11331
#define IDC_BTN_CopyValue               11341
#define IDC_EDIT_GzSwitch               11351
#define IDC_EDIT_gz_P                   11361
#define IDC_EDIT_gz_I                   11371
#define IDC_EDIT_gz_D                   11381
#define IDC_BTN_SendYjData              11391
#define IDC_CHECK_GdSwitch              11421
#define IDC_EDIT_gd                     11431
#define IDC_EDIT_aimGd                  11441
#define IDC_EDIT_gdRPV                  11451
#define IDC_EDIT_GdSwitch               11461
#define IDC_BTN_SendGdRPV               11471
#define IDC_EDIT_gd_qg_P                11481
#define IDC_EDIT_gd_qg_I                11491
#define IDC_EDIT_gd_qg_D                11501
#define IDC_EDIT_GPSgd                  11511
#define IDC_EDIT_gd_agl_P               11531
#define IDC_EDIT_gd_agl_I               11541
#define IDC_EDIT_gd_agl_D               11551
#define IDC_EDIT_VP                     11561
#define ID_MENU_SETTING                 32771
#define ID_MENU_MOUSE_ARROW             32773
#define ID_MENU_MOUSE_ENLARGE           32774
#define ID_MENU_MOUSE_ZOOMIN_BIG        32774
#define ID_MENU_MOUSE_REDUCE            32775
#define ID_MENU_MOUSE_ZOOMOUT_SMALL     32775
#define ID_MENU_MOUSE_MOVE              32776
#define ID_MENU_MOUSE_CENTER            32777
#define ID_MENU_MOUSE_SELECT_MOVE       32778
#define ID_MENU_MOUSE_INSERT_WAYPOINT   32779
#define ID_MENU_MOUSE_WAYPOINT_INSERT   32779
#define ID_MENU_MOUSE_INSERT_WAYLINE    32780
#define ID_MENU_MOUSE_WAYLINE_INSERT    32780
#define ID_MENU_MOUSE_EDIT_WAYPOINT     32781
#define ID_MENU_MOUSE_WAYPOINT_EDIT     32781
#define ID_MENU_MOUSE_UPLOAD_WAYPOINT   32782
#define ID_MENU_MOUSE_WAYPOINT_UPLOAD   32782
#define ID_MENU_MOUSE_SIGN              32783
#define ID_MENUITEM32785                32785
#define ID_MENU_LISTEN                  32785
#define ID_MENUITEM32786                32786
#define ID_MENU_PLAYBACK                32786
#define ID_MENUITEM32787                32787
#define ID_MENU_PHOTOLOCATION           32787
#define ID_MENUITEM32788                32788
#define ID_MENU_DOWN_TELEMETRY          32788
#define ID_MENUITEM32789                32789
#define ID_MENU_DOWN_STEERING           32789
#define ID_MENUITEM32790                32790
#define ID_MENU_DOWN_GPS                32790
#define ID_MENUITEM32791                32791
#define ID_MENU_DOWN_SENSOR             32791
#define ID_MENUITEM32792                32792
#define ID_MENU_DOWN_MIDDLE             32792
#define ID_MENUITEM32793                32793
#define ID_MENU_OPEN_RECEIVER           32793
#define ID_MENUITEM32794                32794
#define ID_MENU_CLOSE_RECEIVER          32794
#define ID_MENU_MIDDLE_VALUE            32795
#define ID_MENU_MAX_WINDDOOR            32796
#define ID_MENU_MIN_WINDDOOR            32797
#define ID_MENU_STOPCAR_POSITION        32798
#define ID_TOOL_DISTANCE                32799
#define ID_TOOL_DOWN_PHOTODATA          32800
#define ID_TOOL_INQUIRE_PHOTONUM        32801
#define ID_TOOL_HANDPHOTOONE            32802
#define ID_TOOL_DOWN_WAYPOINT           32803
#define ID_TOOL_LAYER                   32804
#define ID_TOOL_STARTCONTINUEPHOTO      32805
#define ID_TOOL_STOPCONTINUEPHOTO       32806
#define ID_BUTTON32807                  32807
#define ID_TOOL_CENTER                  32813
#define ID_TOOL_WAYLINE                 32814
#define ID_TOOL_CLEAN_TRACK             32815
#define ID_BUTTON32816                  32816
#define ID_TOOL_SHOW_UAV_WAYPOINT       32817
#define ID_BUTTON32818                  32818
#define ID_                             32819
#define ID_TOOL_RECT                    32822
#define ID_TOOL_CLEAN_UAV_WAYPOINT      32823
#define ID_TOOL_WAYPOINT_COPYDOWN_TOUP  32824
#define ID_TOOL_PROMPT_WAYLINE          32825
#define ID_TOOL_MOUSE_WAYPOINT          32827
#define ID_BUTTON32829                  32829
#define ID_TOOL_EDIT_WAYPOINT           32830
#define ID_BUTTON32831                  32831
#define ID_BUTTON32832                  32832
#define ID_BUTTON32833                  32833
#define ID_BUTTON32834                  32834
#define ID_BUTTON32835                  32835
#define ID_BUTTON32836                  32836
#define ID_TOOL_SIGN_POINT              32837
#define ID_TOOL_SIGN_LINE               32838
#define ID_TOOL_SIGN_POLYLINE           32840
#define ID_TOOL_SIGN_POLY               32842
#define ID_TOOL_UP_WAYPOINT             32843
#define ID_TOOL_WAYPOINTDOWN_HIDE       32845
#define ID_TOOL_WAYPOINT_EDIT           32847
#define ID_MENU_MOUSE_WAYPOINT_DELETE   32849
#define ID_MENU_TAKEOFF_CHECK           32850
#define ID_MENU_CLOSE                   32851
#define ID_TOOL_STANDARDWAYLINE         32852
#define ID_MENU_PID                     32853
#define IDS_TIP_RECEIVEDPACKETTYPE      57345
#define IDS_TIP_TOGGLE_RECEIVER         57346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
