// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_meter.h"

// Dispatch interfaces referenced by this interface
#include "picture.h"
#include "font.h"

/////////////////////////////////////////////////////////////////////////////
// C_Meter

IMPLEMENT_DYNCREATE(C_Meter, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_Meter properties

/////////////////////////////////////////////////////////////////////////////
// C_Meter operations

void C_Meter::ShowAbout()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long C_Meter::LoadFromLibrary(LPCTSTR Description)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x60030056, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Description);
	return result;
}

void C_Meter::RefreshStatic()
{
	InvokeHelper(0x60030068, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void C_Meter::RefreshDynamic()
{
	InvokeHelper(0x6003006a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL C_Meter::GetAutoRedraw()
{
	BOOL result;
	InvokeHelper(0x68030055, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAutoRedraw(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030055, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

unsigned long C_Meter::GetBackColor()
{
	unsigned long result;
	InvokeHelper(0x68030054, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetBackColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030054, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL C_Meter::GetEnabled()
{
	BOOL result;
	InvokeHelper(DISPID_ENABLED, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Meter::SetEnabled(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(DISPID_ENABLED, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CPicture C_Meter::GetMouseIcon()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x68030053, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPicture(pDispatch);
}

void C_Meter::SetRefMouseIcon(LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x68030053, DISPATCH_PROPERTYPUTREF, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetMousePointer()
{
	long result;
	InvokeHelper(0x68030052, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetMousePointer(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030052, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetBorderWidth()
{
	long result;
	InvokeHelper(0x68030051, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetBorderWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030051, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

unsigned long C_Meter::GetBorderColor()
{
	unsigned long result;
	InvokeHelper(0x68030050, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetBorderColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030050, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetOutLineStyle()
{
	long result;
	InvokeHelper(0x6803004f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetOutLineStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetInLineStyle()
{
	long result;
	InvokeHelper(0x6803004e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetInLineStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

unsigned long C_Meter::GetBorderLight()
{
	unsigned long result;
	InvokeHelper(0x6803004d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetBorderLight(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetBorderShadow()
{
	unsigned long result;
	InvokeHelper(0x6803004c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetBorderShadow(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetOutLineWidth()
{
	long result;
	InvokeHelper(0x6803004b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetOutLineWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetInLineWidth()
{
	long result;
	InvokeHelper(0x6803004a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetInLineWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803004a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CPicture C_Meter::GetBackPicture()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x68030049, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPicture(pDispatch);
}

void C_Meter::SetRefBackPicture(LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x68030049, DISPATCH_PROPERTYPUTREF, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetHandNum()
{
	long result;
	InvokeHelper(0x68030048, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030048, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

double C_Meter::GetHandValue()
{
	double result;
	InvokeHelper(0x68030047, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandValue(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030047, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetHandID()
{
	long result;
	InvokeHelper(0x68030046, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030046, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void C_Meter::SetHandPanelID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030045, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetHandPanelID()
{
	long result;
	InvokeHelper(0x68030045, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030044, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetHandColor()
{
	unsigned long result;
	InvokeHelper(0x68030044, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030043, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetHandStyle()
{
	long result;
	InvokeHelper(0x68030043, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030042, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetHandWidth()
{
	long result;
	InvokeHelper(0x68030042, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandRadius(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030041, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetHandRadius()
{
	double result;
	InvokeHelper(0x68030041, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandShadow(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030040, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetHandShadow()
{
	unsigned long result;
	InvokeHelper(0x68030040, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandMouseControl(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803003f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetHandMouseControl()
{
	long result;
	InvokeHelper(0x6803003f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandDigitalDecimals(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803003e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetHandDigitalDecimals()
{
	long result;
	InvokeHelper(0x6803003e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandDigitalColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803003d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetHandDigitalColor()
{
	unsigned long result;
	InvokeHelper(0x6803003d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandDigitalX(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803003c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetHandDigitalX()
{
	double result;
	InvokeHelper(0x6803003c, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandDigitalFontID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803003b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetHandDigitalFontID()
{
	long result;
	InvokeHelper(0x6803003b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

double C_Meter::GetHandDigitalY()
{
	double result;
	InvokeHelper(0x6803003a, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandDigitalY(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803003a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL C_Meter::GetHandDigitalVisible()
{
	BOOL result;
	InvokeHelper(0x68030039, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Meter::SetHandDigitalVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x68030039, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

long C_Meter::GetPanelNum()
{
	long result;
	InvokeHelper(0x68030038, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030038, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetPanelID()
{
	long result;
	InvokeHelper(0x68030037, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030037, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void C_Meter::SetRefPanelPicture(LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x68030036, DISPATCH_PROPERTYPUTREF, VT_EMPTY, NULL, parms,
		 newValue);
}

CPicture C_Meter::GetPanelPicture()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x68030036, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPicture(pDispatch);
}

void C_Meter::SetPanelColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030035, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetPanelColor()
{
	unsigned long result;
	InvokeHelper(0x68030035, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

double C_Meter::GetPanelOriginX()
{
	double result;
	InvokeHelper(0x68030034, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelOriginX(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030034, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetPanelOriginY()
{
	double result;
	InvokeHelper(0x68030033, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelOriginY(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030033, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetPanelBorderWidth()
{
	long result;
	InvokeHelper(0x68030032, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelBorderWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030032, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetPanelBorderStyle()
{
	long result;
	InvokeHelper(0x68030031, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelBorderStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030031, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

double C_Meter::GetPanelStartAngle()
{
	double result;
	InvokeHelper(0x68030030, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelStartAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030030, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetPanelEndAngle()
{
	double result;
	InvokeHelper(0x6803002f, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelEndAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803002f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetPanelBorderLight()
{
	double result;
	InvokeHelper(0x6803002e, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelBorderLight(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803002e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetPanelDirection()
{
	long result;
	InvokeHelper(0x6803002d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelDirection(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803002d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

double C_Meter::GetPanelMin()
{
	double result;
	InvokeHelper(0x6803002c, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelMin(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803002c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetPanelMax()
{
	double result;
	InvokeHelper(0x6803002b, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelMax(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803002b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetPanelBorderColor()
{
	unsigned long result;
	InvokeHelper(0x6803002a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelBorderColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803002a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetPanelRadius()
{
	double result;
	InvokeHelper(0x68030029, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelRadius(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030029, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetPanelStyle()
{
	long result;
	InvokeHelper(0x68030028, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetPanelStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030028, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicNum()
{
	long result;
	InvokeHelper(0x68030027, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030027, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicID()
{
	long result;
	InvokeHelper(0x68030026, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030026, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void C_Meter::SetTicPanelID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030025, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicPanelID()
{
	long result;
	InvokeHelper(0x68030025, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicLineNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030024, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicLineNum()
{
	long result;
	InvokeHelper(0x68030024, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicLineWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030023, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicLineWidth()
{
	long result;
	InvokeHelper(0x68030023, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicLineLength(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030022, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicLineLength()
{
	long result;
	InvokeHelper(0x68030022, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicNumberColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030021, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetTicNumberColor()
{
	unsigned long result;
	InvokeHelper(0x68030021, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicNumberFontID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030020, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicNumberFontID()
{
	long result;
	InvokeHelper(0x68030020, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicNumerical(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x6803001f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL C_Meter::GetTicNumerical()
{
	BOOL result;
	InvokeHelper(0x6803001f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicLineRadius(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803001e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetTicLineRadius()
{
	double result;
	InvokeHelper(0x6803001e, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicNumberRadius(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803001d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetTicNumberRadius()
{
	double result;
	InvokeHelper(0x6803001d, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicLineColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803001c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetTicLineColor()
{
	unsigned long result;
	InvokeHelper(0x6803001c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicMaxNumber(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803001b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetTicMaxNumber()
{
	double result;
	InvokeHelper(0x6803001b, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicMinNumber(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803001a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetTicMinNumber()
{
	double result;
	InvokeHelper(0x6803001a, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicNumberFormat(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030019, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

CString C_Meter::GetTicNumberFormat()
{
	CString result;
	InvokeHelper(0x68030019, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicLineStyle(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030018, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetTicLineStyle()
{
	long result;
	InvokeHelper(0x68030018, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicEndAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030017, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetTicEndAngle()
{
	double result;
	InvokeHelper(0x68030017, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetTicStartAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030016, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetTicStartAngle()
{
	double result;
	InvokeHelper(0x68030016, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

long C_Meter::GetAnnularNum()
{
	long result;
	InvokeHelper(0x68030015, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030015, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetAnnularID()
{
	long result;
	InvokeHelper(0x68030014, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030014, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetAnnularPanelID()
{
	long result;
	InvokeHelper(0x68030013, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularPanelID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030013, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void C_Meter::SetAnnularOuter(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030012, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetAnnularOuter()
{
	double result;
	InvokeHelper(0x68030012, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularInner(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030011, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetAnnularInner()
{
	double result;
	InvokeHelper(0x68030011, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularEndAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetAnnularEndAngle()
{
	double result;
	InvokeHelper(0x68030010, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularStartAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetAnnularStartAngle()
{
	double result;
	InvokeHelper(0x6803000f, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetAnnularColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

unsigned long C_Meter::GetAnnularColor()
{
	unsigned long result;
	InvokeHelper(0x6803000e, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long C_Meter::GetCaptionNum()
{
	long result;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetCaptionID()
{
	long result;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString C_Meter::GetCaptionText()
{
	CString result;
	InvokeHelper(0x6803000b, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionText(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6803000b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

unsigned long C_Meter::GetCaptionColor()
{
	unsigned long result;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionColor(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6803000a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetCaptionFontID()
{
	long result;
	InvokeHelper(0x68030009, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionFontID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030009, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

double C_Meter::GetCaptionX()
{
	double result;
	InvokeHelper(0x68030008, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionX(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030008, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetCaptionY()
{
	double result;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionY(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030007, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

double C_Meter::GetCaptionAngle()
{
	double result;
	InvokeHelper(0x68030006, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, NULL);
	return result;
}

void C_Meter::SetCaptionAngle(double newValue)
{
	static BYTE parms[] =
		VTS_R8;
	InvokeHelper(0x68030006, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetFontNum()
{
	long result;
	InvokeHelper(0x68030005, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetFontNum(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030005, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long C_Meter::GetFontID()
{
	long result;
	InvokeHelper(0x68030004, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void C_Meter::SetFontID(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68030004, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

COleFont C_Meter::GetFont()
{
	LPDISPATCH pDispatch;
	InvokeHelper(DISPID_FONT, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return COleFont(pDispatch);
}

void C_Meter::SetRefFont(LPDISPATCH newValue)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(DISPID_FONT, DISPATCH_PROPERTYPUTREF, VT_EMPTY, NULL, parms,
		 newValue);
}

long C_Meter::GetHWnd()
{
	long result;
	InvokeHelper(0x68030003, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long C_Meter::GetHDC()
{
	long result;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CPicture C_Meter::GetImage()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x68030001, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPicture(pDispatch);
}

CString C_Meter::GetLibraryDescription()
{
	CString result;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_Meter::SetLibraryDescription(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030000, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}
