//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TF1D.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_STATIC1                     101
#define IDD_UP20_DIALOG                 102
#define IDC_STATIC2                     102
#define IDR_MAINFRAME                   128
#define IDR_MENU                        133
#define IDR_TOOLBAR                     150
#define IDB_BITMAP1                     152
#define IDI_SUNBIRD                     153
#define IDI_LEDOFF                      154
#define IDI_LEDON                       155
#define IDI_LEDWAR                      156
#define IDB_BITMAP2                     162
#define IDI_ICON1                       163
#define IDI_ICON2                       164
#define IDI_ZOOMIN                      165
#define IDI_ZOOMOUT                     166
#define IDI_MOVE                        167
#define IDI_SELECT                      168
#define IDI_LAYERSCTR                   170
#define IDI_DISTANCE                    171
#define IDI_SELECTRECT                  172
#define IDI_AIROW                       173
#define IDI_POINTS                      174
#define IDR_MENUMOUSE                   175
#define IDD_PORTSET                     177
#define IDD_UAVSET                      182
#define IDD_SAFESET                     183
#define IDD_POTDATA                     184
#define IDI_POTDATA                     185
#define IDD_LAYERSCTR                   186
#define IDD_RANGEPOD                    190
#define IDI_RANGEPOINTS                 191
#define IDI_UPPOINTS                    192
#define IDI_DOWNPOINTS                  193
#define IDD_PHOTOSET                    195
#define IDD_BTSET                       196
#define IDD_ALTSET                      197
#define IDD_AIRTOZERO                   198
#define IDR_HTML1                       199
#define IDD_DOWNPOINTS                  200
#define IDI_LIANPAI                     201
#define IDI_LIANPAIOFF                  202
#define IDI_HEADINGPHOTO                203
#define IDI_DOWNPHOTODATA               204
#define IDI_ASKPHOTONUM                 205
#define IDB_BITMAP4                     216
#define IDB_BITMAP3                     217
#define IDB_BITMAP5                     218
#define IDB_BITMAP6                     220
#define IDI_COPYPOINTS                  221
#define IDI_ICON3                       222
#define IDB_BITMAP7                     223
#define IDD_LINECOMPUTER                225
#define IDC_METER2                      1006
#define IDC_METER_ALT                   1006
#define IDC_METER3                      1007
#define IDC_METER_SPD                   1007
#define IDC_METER4                      1008
#define IDC_METER_HEAD                  1008
#define IDC_METER5                      1009
#define IDC_METER_RPM                   1009
#define IDC_AIRCTRL                     1015
#define IDC_ZOOMOUT                     1021
#define IDC_ZOOMIN                      1022
#define IDC_MOVE                        1023
#define IDC_SELECT                      1024
#define IDC_SELECTRECT                  1025
#define IDC_LAYERSCTR                   1026
#define IDC_AIROW                       1027
#define IDC_POINTS                      1028
#define IDC_MAP1                        1032
#define IDC_COM                         1037
#define IDC_BT                          1038
#define IDC_DISTANCE                    1041
#define IDC_TIME                        1042
#define IDC_TYPE                        1043
#define IDC_PHOTOSET                    1044
#define IDC_ALTTOGROUND                 1048
#define IDC_AIRTOZERO                   1049
#define IDC_ALTSET                      1051
#define IDC_MSCOMM                      1062
#define IDC_MSCOMM1                     1063
#define IDC_BTSET                       1065
#define IDC_PASHENGMIN                  1066
#define IDC_PASHENGMAX                  1067
#define IDC_HIGHMIN                     1068
#define IDC_AIRMIN                      1069
#define IDC_AIRMAX                      1070
#define IDC_UAVVMIN                     1071
#define IDC_UAVVMAX                     1072
#define IDC_SERVVMIN                    1073
#define IDC_SERVVMAX                    1074
#define IDC_SCROLLBAR                   1081
#define IDC_MODEL_ALT                   1087
#define IDC_MODEL_SPD                   1088
#define IDC_MODEL_RAID                  1089
#define IDC_MODEL_TIME                  1090
#define IDC_MODEL_LINETYPE              1091
#define IDC_CHECK_TOLINE                1092
#define IDC_POTDATA                     1093
#define IDC_CHECK_TOGROUND              1093
#define IDC_CHECK_TOSLIDE               1094
#define IDC_DIRECTER                    1094
#define IDC_CHECK_PHOTO                 1095
#define IDC_NEWLAYER                    1095
#define IDC_CHECK_SERV1                 1096
#define IDC_OPENLAYER                   1096
#define IDC_CHECK_SEVER2                1097
#define IDC_OPENMAP                     1097
#define IDC_CHECK_SERV3                 1098
#define IDC_COMMONDIALOG1               1098
#define IDC_ALT1                        1099
#define IDC_COMMONDIALOG2               1099
#define IDC_EDIT1                       1100
#define IDC_SPD1                        1100
#define IDC_DATASTYLE                   1100
#define IDC_EDIT2                       1101
#define IDC_RAID1                       1101
#define IDC_FREQUENCY                   1101
#define IDC_LINEDIEPIAN                 1101
#define IDC_TIME1                       1102
#define IDC_EDIT3                       1103
#define IDC_LINETYPE1                   1103
#define IDC_POINTTARGET                 1103
#define IDC_RECEIVE                     1103
#define IDC_PHOTODIEPIAN                1103
#define IDC_TOLINE1                     1104
#define IDC_LAYERCONTRAL                1105
#define IDC_TOGROUND1                   1105
#define IDC_TOSLIDE1                    1106
#define IDC_CHECKLINE                   1107
#define IDC_PHOTO1                      1107
#define IDC_CHECKMAPSELECTABLE          1108
#define IDC_SERV11                      1108
#define IDC_SECOND_LAT                  1109
#define IDC_SEVER21                     1109
#define IDC_IN_DIS                      1110
#define IDC_SERV31                      1110
#define IDC_LINENUM                     1111
#define IDC_ALT2                        1111
#define IDC_FIRST_LON                   1112
#define IDC_SPD2                        1112
#define IDC_FIRST_LAT                   1113
#define IDC_RAID2                       1113
#define IDC_SECOND_LON                  1114
#define IDC_TIME2                       1114
#define IDC_RANGEPOINTS                 1115
#define IDC_LINETYPE2                   1115
#define IDC_POINTDIS                    1116
#define IDC_TOLINE2                     1116
#define IDC_PITCH                       1117
#define IDC_TOGROUND2                   1117
#define IDC_HEADING                     1118
#define IDC_TOSLIDE2                    1118
#define IDC_ROLL                        1119
#define IDC_PHOTO2                      1119
#define IDC_SERV12                      1120
#define IDC_POINTTARGETSEND             1120
#define IDC_SEVER22                     1121
#define IDC_SENDTARGETPOINT             1121
#define IDC_CLOSERECEIVE                1122
#define IDC_SERV32                      1122
#define IDC_EDIT8                       1123
#define IDC_ALT3                        1123
#define IDC_CPVHEADINGNUM               1123
#define IDC_PHOTOWIDTH                  1123
#define IDC_BUTTON4                     1124
#define IDC_SPD3                        1124
#define IDC_CPVHEADING                  1124
#define IDC_EDIT9                       1125
#define IDC_RAID3                       1125
#define IDC_CPVALTNUM                   1125
#define IDC_BUTTON5                     1126
#define IDC_TIME3                       1126
#define IDC_CPVALT                      1126
#define IDC_EDIT10                      1127
#define IDC_LINETYPE3                   1127
#define IDC_CPVSPDNUM                   1127
#define IDC_FORTIME                     1127
#define IDC_BUTTON6                     1128
#define IDC_TOLINE3                     1128
#define IDC_CPVSPEED                    1128
#define IDC_BUTTON7                     1129
#define IDC_TOGROUND3                   1129
#define IDC_OPENCPV                     1129
#define IDC_TOSLIDE3                    1130
#define IDC_PHOTO3                      1131
#define IDC_SERV13                      1132
#define IDC_SEVER23                     1133
#define IDC_SERV33                      1134
#define IDC_ALT4                        1135
#define IDC_SPD4                        1136
#define IDC_RAID4                       1137
#define IDC_TIME4                       1138
#define IDC_LINETYPE4                   1139
#define IDC_TOLINE4                     1140
#define IDC_TOGROUND4                   1141
#define IDC_TOSLIDE4                    1142
#define IDC_PHOTO4                      1143
#define IDC_SERV14                      1144
#define IDC_SEVER24                     1145
#define IDC_SERV34                      1146
#define IDC_ALT5                        1147
#define IDC_SPD5                        1148
#define IDC_RAID5                       1149
#define IDC_TIME5                       1150
#define IDC_LINETYPE5                   1151
#define IDC_TOLINE5                     1152
#define IDC_TOGROUND5                   1153
#define IDC_TOSLIDE5                    1154
#define IDC_PHOTO5                      1155
#define IDC_SERV15                      1156
#define IDC_SEVER25                     1157
#define IDC_SERV35                      1158
#define IDC_ALT6                        1159
#define IDC_SPD6                        1160
#define IDC_RAID6                       1161
#define IDC_TIME6                       1162
#define IDC_LINETYPE6                   1163
#define IDC_TOLINE6                     1164
#define IDC_TOGROUND6                   1165
#define IDC_TOSLIDE6                    1166
#define IDC_PHOTO6                      1167
#define IDC_SERV16                      1168
#define IDC_SEVER26                     1169
#define IDC_SERV36                      1170
#define IDC_LON1                        1171
#define IDC_LAT1                        1172
#define IDC_LON2                        1173
#define IDC_LAT2                        1174
#define IDC_LON3                        1175
#define IDC_LAT3                        1176
#define IDC_LON4                        1177
#define IDC_LAT4                        1178
#define IDC_LON5                        1179
#define IDC_LAT5                        1180
#define IDC_LON6                        1181
#define IDC_LAT6                        1182
#define IDC_NUM1                        1183
#define IDC_NUM3                        1184
#define IDC_NUM4                        1185
#define IDC_DOWNLOADPOINTS              1185
#define IDC_NUM5                        1186
#define IDC_COMBO_TYPE                  1186
#define IDC_NUM6                        1187
#define IDC_ALT                         1187
#define IDC_COMBO_BT                    1188
#define IDC_DIS                         1189
#define IDC_NUM2                        1190
#define IDC_POTNUM                      1190
#define IDC_SERIATEPHOTO                1191
#define IDC_SERIATEPHOTOSTOP            1192
#define IDC_HEADINGPHOTO                1193
#define IDC_DOWNPHOTODATA               1194
#define IDC_ASKPHOTONUM                 1195
#define IDC_PHOTONUM                    1196
#define IDC_CHECKUPLINE                 1197
#define IDC_CHECKREALLINE               1198
#define IDC_SPEEDSLIDER                 1200
#define IDC_COPYPOINTS                  1201
#define IDC_BEGAINFLY                   1202
#define IDC_FLYSPEED                    1203
#define IDC_SITESLIDE                   1206
#define IDC_SHOWSPEED                   1208
#define IDC_SHOWSITE                    1209
#define IDC_TOTALDIS                    1210
#define IDC_BPLAYSITE                   1211
#define IDC_ANGLEGET                    1212
#define IDC_ANGLESET                    1213
#define IDC_JINGTOU                     1216
#define IDC_LENGTH                      1217
#define IDC_WIDTH                       1218
#define IDC_FENBIANLV                   1219
#define IDC_PHOTOLENGTH                 1220
#define IDC_FORPHOTONUM                 1221
#define IDC_LINEDIS                     1222
#define IDC_PHOTODIS                    1223
#define ID_DATAGET                      32773
#define ID_TOOL                         32785
#define ID_BUTTON32790                  32790
#define ID_BUTTON32791                  32791
#define ID_BUTTON32792                  32792
#define ID_BUTTON32793                  32793
#define ID_BUTTON32794                  32794
#define ID_BUTTON32797                  32797
#define ID_PICSHOW                      32798
#define ID_DATASHOW                     32799
#define ID_PORTSET                      32800
#define ID_UAVSET                       32801
#define ID_SAFESET                      32804
#define ID_YAOCEDATA                    32805
#define ID_DUOJIDATA                    32806
#define ID_ZHONGLI                      32807
#define ID_INSERTPOINT                  32808
#define ID_UPLOADPOINT                  32809
#define ID_PHOTOSET                     32810
#define ID_ALTSET                       32811
#define ID_BTSET                        32812
#define ID_AIRTOZERO                    32813
#define ID_MENU_BUHUO_ZHONGLI           32814
#define ID_MENU_BUHUO_MAXOIL            32815
#define ID_MENU_BUHUO_MINOIL            32816
#define ID_MENU_BUHUO_STOPOIL           32817
#define ID_UPLOADSOMEPOINT              32818
#define ID_YAOCEDATASTOP                32819
#define ID_MENUITEM_COMPUTER            32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1224
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
